package com.pengurus.crm.shared.dto;

public enum UserRoleDTO {
    
	ROLE_ACCOUNTANT,
	ROLE_EXECUTIVE,
	ROLE_EXPERT,
	ROLE_FREELANCER,
	ROLE_USER,
	ROLE_CLIENT,
	ROLE_VERIFICATOR,
	ROLE_PROJECTMNAGER;    
	
}
